DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS LIBRARIAN;

create table LIBRARIAN (
ID INT AUTO_INCREMENT PRIMARY KEY,
FULL_NAME VARCHAR(300) NOT NULL
);

create table USER (
ID INT AUTO_INCREMENT PRIMARY KEY,
USER_ID VARCHAR(200),
PASSWORD VARCHAR(200),
ROLE VARCHAR(200)
);

INSERT INTO LIBRARIAN (FULL_NAME) values ('Admin User');
INSERT INTO USER (USER_ID, PASSWORD, ROLE) values ('admin', 'admin', 'ADMIN');
INSERT INTO LIBRARIAN (FULL_NAME) values ('Library User');
INSERT INTO USER (USER_ID, PASSWORD, ROLE) values ('lib', 'lib', 'LIBRARIAN');